name: GitHub pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true

      - name: Install dependencies
        run: |
          cd book
          gem install bundler
          bundle install

      - name: Build the docs
        run: |
          cd book
          ./generate.sh main.adoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/dist
